pipeline {
  agent any
  stages {
    stage('Terraform Apply') {
      steps {
        dir('terraform') {
          sh '''
            docker run --rm -v $PWD:/workspace -w /workspace hashicorp/terraform:latest init
            docker run --rm -v $PWD:/workspace -w /workspace hashicorp/terraform:latest apply -auto-approve
          '''
        }
      }
    }
    stage('Build Docker Image') {
      steps {
        dir('docker') {
          sh 'docker build -t radha-app .'
        }
      }
    }
    stage('Run Docker Container') {
      steps {
        sh 'docker run -d -p 8080:80 radha-app'
      }
    }
  }
}
