pipeline {
  agent any
  stages {
    stage('Clone Repo') {
      steps {
        git 'https://github.com/NagadurgaRadhadevi/devops-aws-terraform-jenkins-project.git'
      }
    }
    stage('Terraform Apply') {
      steps {
        dir('terraform') {
          sh 'terraform init'
          sh 'terraform apply -auto-approve'
        }
      }
    }
    stage('Build Docker Image') {
      steps {
        dir('docker') {
          sh 'docker build -t radha-app .'
        }
      }
    }
    stage('Run Docker Container') {
      steps {
        sh 'docker run -d -p 8080:80 radha-app'
      }
    }
  }
}